version: "3.7"

networks:
  loki:

volumes:
  prometheus:
  grafana:
  app-python-visits:

services:
  loki:
    image: grafana/loki:2.9.4
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/config.yml
    volumes:
      - ./loki-config.yml:/etc/loki/config.yml
    logging:
      driver: "json-file"
      options:
        tag: "{{ .Name }}"
        max-size: "100m"
        max-file: "10"
    deploy:
      resources:
        limits:
          memory: "500m"
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.9.4
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
      - ./promtail-config.yml:/etc/promtail/config.yml
    command:
      - "--config.file=/etc/promtail/config.yml"
      - "--config.expand-env=true"
    ports:
      - "9080:9080"
    logging:
      driver: "json-file"
      options:
        tag: "{{ .Name }}"
        max-size: "100m"
        max-file: "10"
    deploy:
      resources:
        limits:
          memory: "500m"
    networks:
      - loki

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    image: grafana/grafana:latest
    volumes:
      - ./grafana-ds.yml:/etc/grafana/provisioning/datasources/ds.yml
      - grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    logging:
      driver: "json-file"
      options:
        tag: "{{ .Name }}"
        max-size: "100m"
        max-file: "10"
    deploy:
      resources:
        limits:
          memory: "500m"
    networks:
      - loki

  prometheus:
    image: prom/prometheus:v2.5.0
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/config.yml
      - prometheus:/prometheus
    command:
      - "--config.file=/etc/prometheus/config.yml"
    ports:
      - "9090:9090"
    logging:
      driver: "json-file"
      options:
        tag: "{{ .Name }}"
        max-size: "100m"
        max-file: "10"
    deploy:
      resources:
        limits:
          memory: "500m"
    networks:
      - loki



  app_python:
    container_name: "app_python"
    image: tufra/moscow-time-app-python:0.0.3
    ports:
      - "80:8080"
    logging:
      driver: "json-file"
      options:
        tag: "{{ .Name }}"
        max-size: "100m"
        max-file: "10"
    deploy:
      resources:
        limits:
          memory: "300m"

  app_kotlin:
    container_name: "app_kotlin"
    image: tufra/moscow-time-app-kotlin:0.0.2
    ports:
      - "81:8000"
    logging:
      driver: "json-file"
      options:
        tag: "{{ .Name }}"
        max-size: "100m"
        max-file: "10"
    deploy:
      resources:
        limits:
          memory: "300m"