version: "3.7"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.9.4
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/config.yml
    volumes:
      - ./loki-config.yml:/etc/loki/config.yml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.9.4
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
      - ./promtail-config.yml:/etc/promtail/config.yml
    command:
      - "--config.file=/etc/promtail/config.yml"
      - "--config.expand-env=true"
    networks:
      - loki

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    image: grafana/grafana:latest
    volumes:
      - ./grafana-ds.yml:/etc/grafana/provisioning/datasources/ds.yml
    ports:
      - "3000:3000"
    networks:
      - loki

  app_python:
    container_name: "app_python"
    image: tufra/moscow-time-app-python:0.0.1
    ports:
      - "80:8080"
    logging:
      driver: "json-file"
      options:
        tag: "{{ .Name }}"

  app_kotlin:
    container_name: "app_kotlin"
    image: tufra/moscow-time-app-kotlin:0.0.1
    ports:
      - "81:8000"
    logging:
      driver: "json-file"
      options:
        tag: "{{ .Name }}"