global:
  scrape_interval: 5s

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'prometheus:9090'

  - job_name: 'loki'
    dns_sd_configs:
      - names:
          - loki
        type: A
        port: 3100

  - job_name: 'promtail'
    dns_sd_configs:
      - names:
          - promtail
        type: A
        port: 9080

  - job_name: 'grafana'
    dns_sd_configs:
      - names:
          - grafana
        type: A
        port: 3000

  - job_name: 'app_python'
    dns_sd_configs:
      - names:
          - app_python
        type: A
        port: 8080

  - job_name: 'app_kotlin'
    dns_sd_configs:
      - names:
          - app_kotlin
        type: A
        port: 8000
