apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-kotlin
spec:
  replicas: 3
  minReadySeconds: 5
  selector:
    matchLabels:
      app: app-kotlin
  template:
    metadata:
      labels:
        app: app-kotlin
    spec:
      containers:
        - name: app-kotlin
          image: tufra/moscow-time-app-kotlin:0.0.2
          ports:
            - containerPort: 8000
