apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-python
spec:
  replicas: 3
  minReadySeconds: 5
  selector:
    matchLabels:
      app: app-python
  template:
    metadata:
      labels:
        app: app-python
    spec:
      containers:
        - name: app-python
          image: tufra/moscow-time-app-python:0.0.2
          ports:
            - containerPort: 8080
