apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: demo.local
      http:
        paths:
          - path: /python
            pathType: Prefix
            backend:
              service:
                name: app-python
                port:
                  number: 81

          - path: /kotlin
            pathType: Prefix
            backend:
              service:
                name: app-kotlin
                port:
                  number: 82